spring:
  ## Persistence ##
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devdb
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1
  ## Dev-tools ##
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
server:
  ## Message errors ##
  error:
    include-message: always
    include-stacktrace: always
logging:
  level:
    root: info
    com.hitomi.hop: debug
    org.hibernate.sql: debug
    org.springframework.data.elasticsearch: debug
management:
  endpoint:
    health:
      show-details: always
