spring:
  application:
    name: hatsu-catalog
    version: @version@
  ## Persistence ##
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  ## REST ##
  jackson:
    default-property-inclusion: non_null
server:
  ## Message errors ##
  error:
    include-message: never
    include-stacktrace: never
logging:
  level:
    root: warn
    com.hitomi.hop: info
